language: go

sudo: required

os:
  - linux

go:
  - tip

cache:
  directories:
    - ${HOME}/.cache/usr
    - ${HOME}/.cache/pip

install:
  - .travis/setup.sh

jobs:
  include:
    - script: .travis/tests/core.sh
    - stage: Documentation
      script: .travis/make_documentation.sh
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        skip_cleanup: true
        local_dir: site
        on:
          branch: master
