language: go

sudo: required

os:
  - linux

go:
  - tip

cache:
  directories:
    - ${HOME}/.cache/usr
    - ${HOME}/.cache/pip

env:
  matrix:
    # Core library Golang tests
    - TASK=test_core
    # Python package tests
    - TASK=test_python

script:
  - .travis/test.sh

after_success:
  - sudo -H apt-get install python
  - sudo -H pip install mkdocs mkdocs-material
  - mkdocs build --verbose --clean --strict

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: site
  on:
    branch: master
