language: go

sudo: required

os:
  - linux

go:
  - tip

cache:
  directories:
    - ${HOME}/.cache/usr
    - ${HOME}/.cache/pip

jobs:
  include:
    - stage: Testing
      script: .travis/tests/core.sh
      script: .travis/tests/python3.sh
    - stage: Documentation
      script: .travis/make_documentation.sh
      deploy:
        provider: pages
        api_key: $GITHUB_TOKEN
        skip_cleanup: true
        on:
          branch: master
