language: go

sudo: required

os:
  - linux

cache:
  apt: true
  directories:
    - ${HOME}/.cache/pip
    - ${HOME}/download

before_install:
  - chmod +x .travis/tests/*.sh

jobs:
  include:
    - stage: Core
      script: .travis/tests/core.sh
      go: "1.10"
    - stage: Core
      script: .travis/tests/core.sh
      go: "tip"
    - stage: CLI
      script: .travis/tests/cli.sh
      go: "1.10"
    - stage: CLI
      script: .travis/tests/cli.sh
      go: "tip"
    - stage: Documentation
      script: .travis/make_documentation.sh
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        skip_cleanup: true
        local_dir: site
        on:
          branch: master
