language: go

go:
  - tip

sudo: required

os:
  - linux

cache:
  directories:
    - ${HOME}/.cache/usr
    - ${HOME}/.cache/pip

jobs:
  include:
    - script: .travis/tests/core.sh
    - stage: Documentation
      script: .travis/make_documentation.sh
      deploy:
        provider: pages
        github_token: $GITHUB_TOKEN
        skip_cleanup: true
        local_dir: site
        on:
          branch: master
