# Project information
site_name: XGP
site_description: 'Genetic programming tool for classification and regression'
site_author: 'Max Halford'
site_url: 'https://maxhalford.github.io/xgp'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/MaxHalford/xgp'

# Copyright
copyright: 'Copyright &copy; 2017 Max Halford'

# Theme
theme:
  name: 'material'
  custom_dir: 'docs/theme'
  logo:
    icon: 'home'
  palette:
    primary: 'blue-grey'
    accent: 'red'
  social:
    - type: 'github'
      link: 'https://github.com/MaxHalford/xgp'

# Pages
pages:
  - Introduction: index.md
  - How it works: how-it-works.md
  - Command-line interface (CLI): cli.md
  - Go API: go.md
  - Python API: python.md
  - Training parameters: training-parameters.md

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - mdx_math

# MathJax JavaScript
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
