# Project information
site_name: xgp
site_description: 'Genetic programming tool for classification and regression'
site_author: 'Max Halford'
site_url: 'https://maxhalford.github.io/xgp'

# Repository
repo_name: 'MaxHalford/xgp'
repo_url: 'https://github.com/MaxHalford/xgp'

# Copyright
copyright: 'Copyright &copy; 2017 Max Halford'

# Theme
theme: 'material'

# Pages
pages:
  - Home: index.md
  - How it works: how-it-works.md
  - CLI: cli.md
  - Go: go.md
  - Python: python.md
  - Training parameters: training-parameters.md

# Extensions
markdown_extensions:
  - admonition
  - codehilite

# Options
extra:
  palette:
    primary: 'indigo'
    accent: 'red'
  social:
    - type: 'github'
      link: 'https://github.com/squidfunk'
