# Project information
site_name: koza
site_description: 'Genetic programming tool for classification and regression'
site_author: 'Max Halford'
site_url: 'https://maxhalford.github.io/koza'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/MaxHalford/koza'

# Copyright
copyright: 'Copyright &copy; 2017 Max Halford'

# Theme
theme: 'material'

# Pages
pages:
  - Introduction: index.md
  - How it works: how-it-works.md
  - Command-line interface (CLI): cli.md
  - Go API: go.md
  - Python API: python.md
  - Training parameters: training-parameters.md

# Extensions
markdown_extensions:
  - admonition
  - codehilite

# Options
extra:
  logo:
    icon: 'home'
  palette:
    primary: 'blue-grey'
    accent: 'red'
  social:
    - type: 'github'
      link: 'https://github.com/MaxHalford/koza'
